### ISSUE TITLE
Ubuntu package lacks dependence to a variety of mono files

### ISSUE THREAD

**Issue by vona** [ralovich/quickroute-linux#2]
amongst others, but maybe not only,  mono-csharp-shell

**Comment by ralovich** [comment]
Please answer the following question to provide someone else a chance to reproduce your problem:
* In your report please include:
*  The log of the program in question.
*  What steps will reproduce the problem?
*  What is the expected output? What do you see instead?
*  What version of Quickroute are you using? On what operating system? Is it pre-built of from sources?

Did you take a look at https://github.com/ralovich/quickroute-linux/issues/1 already? Does that solve your problem?

**Comment by ralovich** [comment]
No reply in 6 years. Closing.
